version: "3.7"

services:
  queries_challenge:
    image: postgres
    container_name: ignite-challenge-database-queries
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=queries_challenge
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
    volumes:
      - challengePG:/data/postgres
volumes:
  challengePG:
    driver: local
